// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TpDiPaolantonioPWA.DAL;

#nullable disable

namespace TpDiPaolantonioPWA.Migrations
{
    [DbContext(typeof(DbmuseoMalbaContext))]
    [Migration("20250622180358_AgregarRelacionUsuarioTicket")]
    partial class AgregarRelacionUsuarioTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Autor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<int?>("NacionalidadId")
                        .HasColumnType("int")
                        .HasColumnName("nacionalidad_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("NacionalidadId");

                    b.ToTable("autor", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("autor_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DescripcionDetalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion_detalle");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_evento");

                    b.Property<string>("Portada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("portada");

                    b.Property<int>("SalaId")
                        .HasColumnType("int")
                        .HasColumnName("sala_id");

                    b.Property<int>("TipoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_id");

                    b.Property<double>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("SalaId");

                    b.HasIndex("TipoId");

                    b.ToTable("evento", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Nacionalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nacionalidad1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("nacionalidad")
                        .IsFixedLength();

                    b.ToTable("nacionalidad", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaObra")
                        .HasColumnType("date")
                        .HasColumnName("fecha_obra");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int")
                        .HasColumnName("id_autor");

                    b.Property<string>("ImagenObra")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imagen_obra");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("nombre_obra")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("IdAutor");

                    b.ToTable("obra", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Pai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("pais", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("nombre_sala")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("sala", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantEntradas")
                        .HasColumnType("int")
                        .HasColumnName("cant_entradas");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento");

                    b.HasIndex("Id_usuario");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("tipo_evento", (string)null);
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Autor", b =>
                {
                    b.HasOne("TpDiPaolantonioPWA.DAL.Pai", "Nacionalidad")
                        .WithMany()
                        .HasForeignKey("NacionalidadId")
                        .HasConstraintName("FK_autor_pais");

                    b.Navigation("Nacionalidad");
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Evento", b =>
                {
                    b.HasOne("TpDiPaolantonioPWA.DAL.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .IsRequired()
                        .HasConstraintName("FK_evento_autor");

                    b.HasOne("TpDiPaolantonioPWA.DAL.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .IsRequired()
                        .HasConstraintName("FK_evento_sala");

                    b.HasOne("TpDiPaolantonioPWA.DAL.TipoEvento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .IsRequired()
                        .HasConstraintName("FK_evento_tipo_evento");

                    b.Navigation("Autor");

                    b.Navigation("Sala");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Obra", b =>
                {
                    b.HasOne("TpDiPaolantonioPWA.DAL.Autor", "IdAutorNavigation")
                        .WithMany("Obras")
                        .HasForeignKey("IdAutor")
                        .IsRequired()
                        .HasConstraintName("FK_obra_autor");

                    b.Navigation("IdAutorNavigation");
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Ticket", b =>
                {
                    b.HasOne("TpDiPaolantonioPWA.DAL.Evento", "IdEventoNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("FK_ticket_evento1");

                    b.HasOne("TpDiPaolantonioPWA.DAL.Usuario", "Usuario")
                        .WithMany("ListadoTicketUsuario")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ticket_usuario");

                    b.Navigation("IdEventoNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Autor", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("TpDiPaolantonioPWA.DAL.Usuario", b =>
                {
                    b.Navigation("ListadoTicketUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
